ops:
  load_envs:
    config:
      MINIO_ADDRESS: 127.0.0.1:9000
      MINIO_ACCESS_KEY: utnDcXmjhoNX6UlS
      MINIO_SECRET_KEY: ErxKy5jOsqlaI9TiIJbuMYH21lqCTQ58
  download_raw_data:
    config:
      bucket_name: protector
      file_name: yt.tsv
  detect_emotions:
    config:
      lang_code: it
      local: it
  run_h_speech:
    config:
      tmp_folder: /home/vbezerra/Documents/TextPlatform/tmp
      model_folder: /home/vbezerra/Documents/TextPlatform/ml_models
      model_name: it/model_it.tar.gz
  create_influx:
    config:
      language: it
      local: it
  upload_influx:
    config:
      bucket_name: twitter-influx
      file_name: yt_it_it.json